CREATE TABLE IF NOT EXISTS incoming_tracks (
    id BIGSERIAL PRIMARY KEY,
    track_uri VARCHAR(255) NOT NULL UNIQUE,
    track_name VARCHAR(255) NOT NULL,
    album_name VARCHAR(255) NOT NULL,
    artist_name VARCHAR(255) NOT NULL,
    release_date DATE,
    duration_ms INTEGER NOT NULL CHECK (duration_ms > 0),
    popularity INTEGER NOT NULL CHECK (popularity BETWEEN 0 AND 100),
    explicit BOOLEAN NOT NULL DEFAULT FALSE,
    added_by VARCHAR(255),
    added_at TIMESTAMPTZ NOT NULL,
    genres VARCHAR(255),
    record_label VARCHAR(255),
    danceability DOUBLE PRECISION CHECK (danceability BETWEEN 0 AND 1),
    energy DOUBLE PRECISION CHECK (energy BETWEEN 0 AND 1),
    musical_key SMALLINT CHECK (musical_key BETWEEN 0 AND 11),
    loudness DOUBLE PRECISION,
    mode SMALLINT CHECK (mode IN (0, 1)),
    speechiness DOUBLE PRECISION CHECK (speechiness BETWEEN 0 AND 1),
    acousticness DOUBLE PRECISION CHECK (acousticness BETWEEN 0 AND 1),
    instrumentalness DOUBLE PRECISION CHECK (instrumentalness BETWEEN 0 AND 1),
    liveness DOUBLE PRECISION CHECK (liveness BETWEEN 0 AND 1),
    valence DOUBLE PRECISION CHECK (valence BETWEEN 0 AND 1),
    tempo DOUBLE PRECISION CHECK (tempo > 0),
    time_signature SMALLINT CHECK (time_signature BETWEEN 1 AND 7)
);

INSERT INTO incoming_tracks (
    track_uri,
    track_name,
    album_name,
    artist_name,
    release_date,
    duration_ms,
    popularity,
    explicit,
    added_by,
    added_at,
    genres,
    record_label,
    danceability,
    energy,
    musical_key,
    loudness,
    mode,
    speechiness,
    acousticness,
    instrumentalness,
    liveness,
    valence,
    tempo,
    time_signature
) VALUES
    (
        'spotify:track:0nJW01T7XtvILxQgC5J7Wh',
        'Notion',
        'Notion',
        'The Rare Occasions',
        '2016-08-05',
        195120,
        84,
        FALSE,
        'spotify-import',
        '2026-03-02T10:45:57+00:00',
        'alternative rock',
        'Elektra',
        0.309,
        0.883,
        9,
        -3.825,
        1,
        0.0808,
        0.0673,
        0.00111,
        0.0849,
        0.312,
        159.488,
        4
    ),
    (
        'spotify:track:3qoftcUZaUOncvIYjFSPdE',
        'Bad Habit',
        'Gemini Rights',
        'Steve Lacy',
        '2022-07-15',
        232114,
        84,
        TRUE,
        'spotify-import',
        '2026-03-02T10:33:26+00:00',
        'r&b',
        'L-M Records',
        0.686,
        0.494,
        1,
        -7.093,
        1,
        0.0355,
        0.6130,
        0.000058,
        0.4020,
        0.7000,
        168.946,
        4
    ),
    (
        'spotify:track:2takcwOaAZWiXQijPHIx7B',
        'No One Noticed',
        'Submarine',
        'The Marias',
        '2024-05-31',
        236906,
        90,
        FALSE,
        'spotify-import',
        '2026-03-01T08:12:00+00:00',
        'bedroom pop',
        'Nice Life/Atlantic',
        0.705,
        0.339,
        7,
        -10.612,
        1,
        0.0278,
        0.5520,
        0.0814,
        0.1200,
        0.4570,
        97.989,
        4
    );
